export enum AnnotationFormatType {
    YOLO = 'YOLO',
    COCO = 'COCO',
     CSV = 'CSV',
    JSON = 'JSON',
    VOC = 'VOC',
    VGG = 'VGG',
    CIFAR10 = 'CIFAR10',
    CIFAR100 = 'CIFAR100',
    CITYSCAPES = 'Cityscapes',
    IMAGENET = 'ImageNet',
    KITTI = 'Kitti',
    LFW = 'LFW',
    OPENIMAGES = 'OpenImages',
    TFRECORD = 'TFRecord',
    MOT = 'MOT',
    WIDER = 'WIDER',
    MARKET1501 = 'Market1501',
    ALL = "ALL"
}